### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by arguiot** [yervandsar/ExpandedTabBar#10]
Use similar interface as iTunes.

![IMG_D402D5747BDE-1](https://user-images.githubusercontent.com/18022260/56076879-75c36600-5e08-11e9-97cb-cc2e5fbe03e2.jpeg)

**Comment by yervandsar** [comment]
Hi @arguiot )
Thanks for your comment, We also thought about it and will work in the future

**Comment by undeaDD** [comment]
Maybe this could help ^^
Link: https://github.com/yervandsar/ExpandedTabBar/compare/master...undeaDD:master

The "ForceTouchGestureRecognizer" could also be replaced with an "LongPressGestureRecognizer" if the Device does not support 3DTouch ;)

PS: Im not gonna look further into this, because I do not really need it :S ... but it would be nice to have for sure ^^
